// <auto-generated />
namespace FIRERISK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fourthh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fourthh));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281331553_fourthh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
